# Project
group=bl4ckscor3.mod.lenientcreepers
version=1.2
minecraft_version=26.1.2
minecraft_min_version=26.1
java_version=25
license=MIT
mod_id=lenientcreepers
mod_name=Lenient Creepers
description=Makes creepers not destroy already dropped items.
mod_author=bl4ckscor3
source_link=https://github.com/bl4ckscor3/LenientCreepers
cf_link=https://www.curseforge.com/minecraft/mc-mods/lenient-creepers

# Common
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1
mdg_version=2.0.141
fcap_version=26.1.3
run_dir=../runs
mixin_version=0.13.3+mixin.0.8.5
mixinextras_version=0.3.5

# NeoForge
neoforge_version=26.1.2.36-beta
neoforge_min_version=26.1

# Fabric
loom_version=1.16-SNAPSHOT
fabric_version=0.147.0+26.1.2
fabric_loader_version=0.19.2
modmenu_version=18.0.0-alpha.8

# Gradle
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false
