modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory

[[mods]] #mandatory
	modId="lenientcreepers" #mandatory
	version="v1.0.1" #mandatory
	displayName="LenientCreepers" #mandatory
	description='''Makes creepers not destroy already dropped items.''' #mandatory
	issueTrackerURL="http://github.com/bl4ckscor3/LenientCreepers/issues"
	displayURL="https://curseforge.com/minecraft/mc-mods/lenient-creepers"
	authors="bl4ckscor3"

[[dependencies.lenientcreepers]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lenientcreepers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"