modLoader="javafml"
loaderVersion="[1,)"
license="MIT https://github.com/bl4ckscor3/LenientCreepers/blob/1.20.2/LICENSE"
issueTrackerURL="http://github.com/bl4ckscor3/LenientCreepers/issues"

[[mods]]
	modId="lenientcreepers"
	version="${file.jarVersion}"
	displayName="LenientCreepers"
	description='''Makes creepers not destroy already dropped items.'''
	displayURL="https://curseforge.com/minecraft/mc-mods/lenient-creepers"
	authors="bl4ckscor3"

[[dependencies.lenientcreepers]]
    modId="neoforge"
    mandatory=true
    versionRange="[20.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lenientcreepers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2,1.21)"
    ordering="NONE"
    side="BOTH"