modLoader="javafml"
loaderVersion="[38,)"
license="GNU GPL v3.0 https://github.com/bl4ckscor3/LenientCreepers/blob/1.18/LICENSE"
issueTrackerURL="http://github.com/bl4ckscor3/LenientCreepers/issues"

[[mods]]
	modId="lenientcreepers"
	version="${file.jarVersion}"
	displayName="LenientCreepers"
	description='''Makes creepers not destroy already dropped items.'''
	displayURL="https://curseforge.com/minecraft/mc-mods/lenient-creepers"
	authors="bl4ckscor3"

[[dependencies.lenientcreepers]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lenientcreepers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"