package bl4ckscor3.mod.lenientcreepers;

import java.util.Arrays;
import java.util.List;

import net.minecraft.entity.Entity;
import net.minecraft.entity.item.EntityItem;
import net.minecraft.entity.monster.EntityCreeper;
import net.minecraftforge.common.config.Config.Type;
import net.minecraftforge.common.config.ConfigManager;
import net.minecraftforge.event.world.ExplosionEvent;
import net.minecraftforge.fml.client.event.ConfigChangedEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

@EventBusSubscriber
@Mod(modid=LenientCreepers.MOD_ID, name=LenientCreepers.NAME, version=LenientCreepers.VERSION, acceptedMinecraftVersions="[" + LenientCreepers.MC_VERSION + "]")
public class LenientCreepers
{
	public static final String MOD_ID = "lenientcreepers";
	public static final String NAME = "Lenient Creepers";
	public static final String VERSION = "v1.0";
	public static final String MC_VERSION = "1.12"; //1.12.1 and 1.12.2 also work

	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		ModMetadata meta = event.getModMetadata();

		meta.authorList = Arrays.asList(new String[]{"bl4ckscor3"});
		meta.autogenerated = false;
		meta.description = "Creepers don't destroy already dropped items.";
		meta.modId = MOD_ID;
		meta.name = NAME;
		meta.version = VERSION;
	}

	@SubscribeEvent
	public static void onExplosionDetonate(ExplosionEvent.Detonate event)
	{
		if(event.getExplosion().getExplosivePlacedBy() != null && event.getExplosion().getExplosivePlacedBy() instanceof EntityCreeper)
		{
			if(!Configuration.onlyWithMobGriefingGamerule || (Configuration.onlyWithMobGriefingGamerule && !event.getExplosion().getExplosivePlacedBy().getEntityWorld().getGameRules().getBoolean("mobGriefing")))
			{
				List<Entity> affected = event.getAffectedEntities();

				for(int i = 0; i < affected.size(); i++)
				{
					if(affected.get(i) instanceof EntityItem)
						affected.remove(i);
				}
			}
		}
	}

	@SubscribeEvent
	public static void onConfigChanged(ConfigChangedEvent event)
	{
		if(event.getModID().equals(MOD_ID))
			ConfigManager.load(MOD_ID, Type.INSTANCE);
	}
}
